[package]
name = "parch_kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.2"
bitflags = "1.3.2"
buddy_system_allocator = "0.8.0"
riscv = "0.7.0"